# Generated by Django 6.0.1 on 2026-03-24 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountabro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='block',
            name='unique_block_pair',
        ),
        migrations.AlterField(
            model_name='match',
            name='category',
            field=models.CharField(max_length=60),
        ),
        migrations.RemoveIndex(
            model_name='matchrequest',
            name='accountabro_categor_6ed507_idx',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporter',
        ),
        migrations.RemoveConstraint(
            model_name='usergoal',
            name='unique_goal_per_profile_category',
        ),
        migrations.RemoveConstraint(
            model_name='checkin',
            name='one_checkin_per_day_per_match',
        ),
        migrations.RemoveConstraint(
            model_name='matchmember',
            name='unique_member_per_match',
        ),
        migrations.RemoveIndex(
            model_name='checkin',
            name='accountabro_profile_a9a871_idx',
        ),
        migrations.RemoveField(
            model_name='match',
            name='end_reason',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_available_for_matching',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='onboarding_complete',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timezone',
        ),
        migrations.AddField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_category',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_per_week',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('blocked', 'Blocked')], default='active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['user', 'checkin_date'], name='accountabro_user_id_0c343a_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(fields=('match', 'user', 'checkin_date'), name='one_checkin_per_day_per_match'),
        ),
        migrations.AddConstraint(
            model_name='matchmember',
            constraint=models.UniqueConstraint(fields=('match', 'user'), name='unique_member_per_match'),
        ),
        migrations.AddField(
            model_name='message',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accountabro.match'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='block',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='block',
            name='blocker',
        ),
        migrations.RemoveField(
            model_name='matchrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='matchrequest',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='matchmember',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='matchmember',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='category',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='note',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='MatchRequest',
        ),
        migrations.DeleteModel(
            name='UserGoal',
        ),
        migrations.DeleteModel(
            name='GoalCategory',
        ),
    ]
