# Generated by Django 6.0.1 on 2026-01-29 21:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('is_sensitive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='accountabro.goalcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=40)),
                ('timezone', models.CharField(default='America/Denver', max_length=64)),
                ('bio', models.CharField(blank=True, max_length=240)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('is_available_for_matching', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=80)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='accountabro.profile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='accountabro.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('canceled', 'Canceled')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_requests', to='accountabro.goalcategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to='accountabro.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'status', 'created_at'], name='accountabro_categor_6ed507_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accountabro.match')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_memberships', to='accountabro.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'profile'), name='unique_member_per_match')],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkin_date', models.DateField(default=django.utils.timezone.localdate)),
                ('result', models.CharField(choices=[('did_it', 'Did it'), ('partial', 'Partial'), ('missed', 'Missed')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='accountabro.goalcategory')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='accountabro.match')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='accountabro.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'checkin_date'], name='accountabro_match_i_854aa6_idx'), models.Index(fields=['profile', 'checkin_date'], name='accountabro_profile_a9a871_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'profile', 'checkin_date'), name='one_checkin_per_day_per_match')],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to='accountabro.profile')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to='accountabro.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block_pair')],
            },
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_per_week', models.PositiveSmallIntegerField(default=3)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('partner', 'Partner only')], default='partner', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_goals', to='accountabro.goalcategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='accountabro.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'category'), name='unique_goal_per_profile_category')],
            },
        ),
    ]
